function cekKhodam() {
  const nameInput = document.getElementById("nameInput").value;
  if (!nameInput) {
    Swal.fire({
      title: "GAK BOLEH KOSONG!😡",
      icon: "error",
      confirmButtonText: "OK",
    });
    return;
  }
  document.getElementById("loading").style.display = "block"; // Tampilkan spinner
  setTimeout(() => {
    const khodams = [
      "Ayam geprek",
      "Mie ayam",
      "Nasi goreng",
      "Mio mirza",
      "Roh baik",
      "Roh hitam",
      "Teh manis solo",
      "Telur asin",
      "Bebek",
      "Whiskas",
      "Ayam warna warni",
      "Facebook",
      "Tiktok",
      "Korek",
      "Monitor",
      "Kayu putih",
      "Kodomo",
      "Oli gardan",
      "Oli samping",
      "Free fire",
      "Alok",
      "Kelly",
      "Keramik alfamart",
      "Siluman based",
      "Programmer",
      "Ps 4",
      "Fuad",
      "Ayam cabe ijo",
      "Teh pucuk",
      "Karbu vespa",
      "Chatgpt",
      "Celana sobek",
      "Sempak firaun",
      "Pepsodent",
      "Es buah",
      "Kera hitam",
      "Vicidior",
      "Rubicon",
      "Dudul",
      "Kunci stang",
      "Ksatria kegelapan",
      "Ciki jaguar",
      "Ayam broiler",
      "Helm scoopy",
      "Knalpot beat",
      "Kapal karam",
      "The gladiator",
      "Kursi goyang",
      "Basreng",
      "Cimol",
      "Dino asli sunda",
      "Vixion racing",
      "Mia khalifa",
      "Momo hirai",
      "Twice",
      "Aespa",
      "Beat karbu",
      "Kentungan pos ronda",
      "Megalodon asli jawa",
      "Sedot wc",
      "Pocong mewinh",
      "Nasi goreng",
      "Mie ayam",
      "Ketoprak",
      "Cicak",
      "Instagram",
      "Bunga angrek asli pontianak",
      "Tahu isi",
      "Baso beranak",
      "Tumbler",
      "Singkong bakar",
      "Gelombang laut",
      "Saber roam",
      "Alucard",
      "Raja kikir",
      "Ratu kikir",
      "Orang ganteng, waspadalah",
      "Raden kian jantan",
      "Sprei bunga",
      "King madrid",
      "Udang goreng",
      "Tahu sumedang",
      "Laba laba sunda",
      "Ombak banyuwangi",
      "Hantu skibidi",
      "Modem wifi",
      "Suki",
      "Raja sigma",
      "Sungut lele",
      "Ratu gyatt",
      "Ban dalem",
      "Ular tangga",
      "Icikiwir",
      "Orang cina",
      "Lontong sayur",
      "King emyu",
      "Jawir",
      "Barongsai",
      "Nasi padang",
      "Ayam goreng",
      "Keramik",
      "Agus batako",
      "Imam piring",
      "Udin galon",
    ];
    const khodam = khodams[Math.floor(Math.random() * khodams.length)];
    document.getElementById("khodamName").innerText = khodam;
    document.getElementById("result").style.display = "block";
    document.getElementById("loading").style.display = "none";
  }, 2000); // Delay untuk simulasi loading
}

function resetForm() {
  document.getElementById("nameInput").value = "";
  document.getElementById("result").style.display = "none";
}

